version: '3'
services:
  postgres:
    image: postgres:14
    container_name: ${COMPOSE_PROJECT_NAME:-default}-seabug-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_ADMIN_PASS:?err}
      PGDATA: /var/lib/postgresql/data/pgdata
      PG_SBUG_USER: ${PG_SBUG_USER:?err}
      PG_SBUG_PASS: ${PG_SBUG_PASS:?err}
    volumes:
      - ${SERVICES_VOL:?err}/pg/data:/var/lib/postgresql/data/pgdata
      - ${PWD}/pg_init:/docker-entrypoint-initdb.d
    networks:
      - seabug
    ports:
      - 5432:5432

networks:
 seabug:
  name: ${COMPOSE_PROJECT_NAME:-default}_seabug
  